export const BOOK_APPOINTMENT="BOOK_APPOINTMENT"
export const CANCEL_APPOINTMENT="CANCEL_APPOINTMENT"
export const HOSPITAL_LIST="HOSPITAL_LIST"
export const SET_HOSPITAL_LIST="SET_HOSPITAL_LIST"
export const SEARCH_HOSPITAL="SEARCH_HOSPITAL"
export const DOCTORS_LIST = "DOCTORS_LIST"
export const SEARCH_DOCTOR_LIST = "SEARCH_DOCTOR_LIST"
export const ACTIVE_LIST = "ACTIVE_LIST"
export const HIGHEST_RATING = "HIGHEST_RATING"




